# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  profiles: production

server:
  port: 9001 # Will probably be ignored when deployed in Tomcat

logging.level:
  ROOT: ERROR
  se.leafcoders.rosette: ERROR

spring.mail:
  testConnection: true
  protocol: smtp
  host: localhost
  port: 1234
  # username: 
  # password: 
  properties:
    mail.smtp.auth: false
    mail.smtp.starttls.enable: false
    # mail.smtp.socketFactory.port:

rosette:
  baseUrl: http://localhost:9001
  jwtSecretToken: tooShort # Don't change this. Override this property in production with environment variable
  fileClientCacheMaxAge: 604800 # One week
