# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  profiles: development

server:
  port: 9000

logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring.datasource:
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: root

rosette:
  baseUrl: http://localhost:9000
