# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  profiles: test

server:
  port: 9000

logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: WARNING

spring.jpa:
  show-sql: true # Show log for each sql query

spring.datasource:
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: root

spring.mail:
  protocol: smtp
  host: localhost
  port: 1234
  properties:
    mail.smtp.auth: false
    mail.smtp.starttls.enable: false

rosette:
  baseUrl: http://localhost:9000
