# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  profiles: production

server:
  port: 80  # Will probably be ignored when deployed in Tomcat

logging.level:
  ROOT: ERROR
  se.leafcoders.rosette: ERROR

multipart:
  max-file-size: 200MB
  max-request-size: 200MB

security:
  basic.enabled: false

spring.data.mongodb:
  database: rosette
  # grid-fs-database:
  host: 127.0.0.1
  port: 27017
  # password:
  # username:

spring.mail:
  protocol: smtp
  host: localhost
  port: 1234
  # username: 
  # password: 
  properties:
    mail.smtp.auth: false
    mail.smtp.starttls.enable: false
    # mail.smtp.socketFactory.port:

rosette:
  baseUrl: http://localhost
  apiVersion: v1
  jwtSecretToken: tooShort # Don't change this. Override this property in production with environment variable
  defaultMailFrom: no-reply@localhost
  uploadCacheMaxAge: 604800 # One week
