version: '3'

services: 
  mysql-database:
    image: mysql:5.7.21
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rosette-db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    volumes:
      - mysql-data:/var/lib/mysql

  rosette-server:
    build: ../..
#    image: leafcoders/rosette
    depends_on:
      - mysql-database
    restart: always
    ports:
      - 9001:9000
    environment:
      #- PORT=9000
      - DATABASE_HOST=mysql-database
      - DATABASE_PORT=3306
      - DATABASE_NAME=rosette-db
      - DATABASE_USERNAME=dbuser
      - DATABASE_PASSWORD=dbpassword
      - MAIL_HOST=
      - MAIL_PORT=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_SMTP_AUTH=false
      - MAIL_SMTP_STARTTLS=false
      - ROSETTE_JWTSECRET=${ROSETTE_JWTSECRET:?Must specify ROSETTE_JWTSECRET in environment}
      - ROSETTE_URL=${ROSETTE_URL:?Must specify ROSETTE_URL in environment}
      - ROSETTE_FILES=/var/lib/rosette
    volumes:
      - rosette-files:/var/lib/rosette

  cordate-client:
    image: leafcoders/cordate:1.1
    depends_on:
      - rosette-server
    restart: always
    ports:
      - 80:80
    environment:
      - ROSETTE_URL=${ROSETTE_URL:?Must specify ROSETTE_URL in environment}
      - APPLICATION_NAME=${CORDATE_APPNAME:?Must specify CORDATE_APPNAME in environment}
    command: /bin/bash -c "envsubst '$$ROSETTE_URL $$APPLICATION_NAME' < /etc/nginx/conf.d/cordate_conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  mysql-data:
  rosette-files:
